### ISSUE TITLE
backend-5-studycompass-web fails to register with Eureka

### ISSUE THREAD

**Issue by ralf-berger** [ude-soco/elas-official#192]
```
/home/app/bin/web: Migrating database ...
==========================================
* Neo4j database connected successfully *
==========================================
==========================================
* Eureka client initialized successfully *
==========================================
[2023-11-23 ...]-[MainThread]-[eureka_client:713] WARNING: Register error! Will try in next heartbeat.
[...]
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/.venv/lib/python3.10/site-packages/py_eureka_client/eureka_client.py", line 710, in register
    await self.__connect_to_eureka_server(do_register)
[...]
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
[2023-11-23 ...]-[MainThread]-[eureka_client:802] WARNING: pull full registry from eureka server error!
[...]
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/.venv/lib/python3.10/site-packages/py_eureka_client/eureka_client.py", line 800, in __pull_full_registry
    await self.__connect_to_eureka_server(do_pull)
[...]
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by ralf-berger** [comment]
* K8s: ok
* Compose: throws error, but is listed as up in Eureka server web UI 🤔
